project:
  type: website

website:
  title: Titanic Survival
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Analysis"
        href: analysis.html
      - text: "Model"
        href: model.html
      - text: "About"
        href: about.html

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css