project:
  type: website

website:
  title: "Titanic Survival Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
      - href: model.qmd
        text: Model

format:
  html:
    theme: cosmo
    toc: true
